# Generated by Django 3.1.3 on 2021-07-21 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0002_auto_20210714_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
