
version: '3.4'

services:
  postgres:
    container_name: postgres_demos
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
